/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketRouteImport } from './routes/market'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SellRouteImport } from './routes/sell'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ApiPublicNowpaymentsRouteImport } from './routes/api/public/nowpayments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNowpaymentsRoute = ApiPublicNowpaymentsRouteImport.update({
  id: '/api/public/nowpayments',
  path: '/api/public/nowpayments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/sell': typeof SellRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/public/nowpayments': typeof ApiPublicNowpaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/sell': typeof SellRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/public/nowpayments': typeof ApiPublicNowpaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/market': typeof MarketRoute
  '/orders': typeof OrdersRoute
  '/sell': typeof SellRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/public/nowpayments': typeof ApiPublicNowpaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/market'
    | '/orders'
    | '/sell'
    | '/verify'
    | '/wallet'
    | '/listings/$id'
    | '/api/public/nowpayments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/market'
    | '/orders'
    | '/sell'
    | '/verify'
    | '/wallet'
    | '/listings/$id'
    | '/api/public/nowpayments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/market'
    | '/orders'
    | '/sell'
    | '/verify'
    | '/wallet'
    | '/listings/$id'
    | '/api/public/nowpayments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MarketRoute: typeof MarketRoute
  OrdersRoute: typeof OrdersRoute
  SellRoute: typeof SellRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ApiPublicNowpaymentsRoute: typeof ApiPublicNowpaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowpayments': {
      id: '/api/public/nowpayments'
      path: '/api/public/nowpayments'
      fullPath: '/api/public/nowpayments'
      preLoaderRoute: typeof ApiPublicNowpaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MarketRoute: MarketRoute,
  OrdersRoute: OrdersRoute,
  SellRoute: SellRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  ListingsIdRoute: ListingsIdRoute,
  ApiPublicNowpaymentsRoute: ApiPublicNowpaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
