REVOKE EXECUTE ON FUNCTION public.admin_list_users() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_list_withdrawals() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_user_role(uuid, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.request_withdrawal(numeric, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.approve_withdrawal(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.reject_withdrawal(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_escrow_order(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.mark_order_shipped(uuid, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.open_dispute(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.release_escrow(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.refund_escrow(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.credit_deposit(uuid, numeric, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.set_deposit_address(uuid, text, text, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;

GRANT EXECUTE ON FUNCTION public.admin_list_users() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_withdrawals() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_role(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_withdrawal(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_withdrawal(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_escrow_order(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_order_shipped(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.open_dispute(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.release_escrow(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refund_escrow(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.credit_deposit(uuid, numeric, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_deposit_address(uuid, text, text, text) TO service_role;